CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');
CREATE TYPE "ProductStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'HIDDEN', 'DISCONTINUED', 'TEMPORARILY_OUT_OF_STOCK');
CREATE TYPE "LeadStatus" AS ENUM ('NEW', 'CONTACTED', 'INTERESTED', 'QUOTE_SENT', 'NEGOTIATION', 'SALE_CONFIRMED', 'PRODUCTION', 'DELIVERY', 'POST_SALE', 'RECURRING_CLIENT', 'LOST');
CREATE TYPE "LeadTemperature" AS ENUM ('COLD', 'WARM', 'HOT');
CREATE TYPE "OrderStatus" AS ENUM ('DRAFT', 'CONFIRMED', 'IN_PRODUCTION', 'READY_FOR_DELIVERY', 'DELIVERED', 'CANCELLED');
CREATE TYPE "ProductionStatus" AS ENUM ('PENDING', 'SCHEDULED', 'IN_MANUFACTURING', 'QUALITY_CONTROL', 'FINISHED', 'READY_FOR_DELIVERY', 'DELIVERED', 'CANCELLED');
CREATE TYPE "DeliveryStatus" AS ENUM ('PENDING', 'SCHEDULED', 'CONFIRMED', 'IN_ROUTE', 'DELIVERED', 'RESCHEDULED', 'CANCELLED');
CREATE TYPE "TaskStatus" AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');
CREATE TYPE "TaskPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
CREATE TYPE "MediaType" AS ENUM ('IMAGE', 'VIDEO', 'DOCUMENT', 'OTHER');

CREATE TABLE roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL UNIQUE, description TEXT, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE TABLE permissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), key TEXT NOT NULL UNIQUE, description TEXT, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, phone TEXT, status "UserStatus" NOT NULL DEFAULT 'ACTIVE', role_id UUID NOT NULL REFERENCES roles(id), created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX users_role_id_idx ON users(role_id);
CREATE TABLE role_permissions (role_id UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE, permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (role_id, permission_id));

CREATE TABLE categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, description TEXT, parent_id UUID REFERENCES categories(id), display_order INTEGER NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX categories_parent_id_idx ON categories(parent_id);
CREATE TABLE colors (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, hex_code TEXT, is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE TABLE products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sku TEXT NOT NULL UNIQUE, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, short_description TEXT, full_description TEXT, brand TEXT, status "ProductStatus" NOT NULL DEFAULT 'DRAFT', is_featured BOOLEAN NOT NULL DEFAULT false, display_order INTEGER NOT NULL DEFAULT 0, meta_title TEXT, meta_description TEXT, og_title TEXT, og_description TEXT, created_by UUID REFERENCES users(id), updated_by UUID REFERENCES users(id), created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX products_status_idx ON products(status);
CREATE INDEX products_is_featured_idx ON products(is_featured);
CREATE TABLE product_categories (product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE, category_id UUID NOT NULL REFERENCES categories(id) ON DELETE CASCADE, is_primary BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (product_id, category_id));
CREATE INDEX product_categories_category_id_idx ON product_categories(category_id);
CREATE TABLE product_variants (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE, color_id UUID REFERENCES colors(id), sku TEXT NOT NULL UNIQUE, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, configuration TEXT, dimensions TEXT, price DECIMAL(12,2), estimated_production_days INTEGER, is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX product_variants_product_id_idx ON product_variants(product_id);
CREATE INDEX product_variants_color_id_idx ON product_variants(color_id);
CREATE TABLE media (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), type "MediaType" NOT NULL DEFAULT 'IMAGE', url TEXT NOT NULL, filename TEXT, mime_type TEXT, size_bytes INTEGER, alt_text TEXT, created_by UUID REFERENCES users(id), created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX media_type_idx ON media(type);
CREATE TABLE product_images (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE, variant_id UUID REFERENCES product_variants(id), media_id UUID REFERENCES media(id), url TEXT NOT NULL, alt_text TEXT, image_type TEXT, is_primary BOOLEAN NOT NULL DEFAULT false, display_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX product_images_product_id_idx ON product_images(product_id);
CREATE INDEX product_images_variant_id_idx ON product_images(variant_id);
CREATE INDEX product_images_media_id_idx ON product_images(media_id);
CREATE TABLE product_relations (product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE, related_product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (product_id, related_product_id));

CREATE TABLE clients (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), first_name TEXT, last_name TEXT, company_name TEXT, email TEXT, phone TEXT, tax_id TEXT, address TEXT, city TEXT, state TEXT, country TEXT DEFAULT 'México', postal_code TEXT, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX clients_email_idx ON clients(email);
CREATE INDEX clients_phone_idx ON clients(phone);
CREATE TABLE leads (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), assigned_user_id UUID REFERENCES users(id), client_id UUID UNIQUE REFERENCES clients(id), first_name TEXT, last_name TEXT, company_name TEXT, email TEXT, phone TEXT, source TEXT, status "LeadStatus" NOT NULL DEFAULT 'NEW', temperature "LeadTemperature", message TEXT, lost_reason TEXT, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX leads_assigned_user_id_idx ON leads(assigned_user_id);
CREATE INDEX leads_status_idx ON leads(status);
CREATE TABLE orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_number TEXT NOT NULL UNIQUE, client_id UUID NOT NULL REFERENCES clients(id), lead_id UUID REFERENCES leads(id), status "OrderStatus" NOT NULL DEFAULT 'DRAFT', subtotal DECIMAL(12,2), total DECIMAL(12,2), notes TEXT, confirmed_at TIMESTAMP(3), created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX orders_client_id_idx ON orders(client_id);
CREATE INDEX orders_lead_id_idx ON orders(lead_id);
CREATE INDEX orders_status_idx ON orders(status);
CREATE TABLE order_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id UUID NOT NULL REFERENCES products(id), variant_id UUID REFERENCES product_variants(id), quantity INTEGER NOT NULL DEFAULT 1, unit_price DECIMAL(12,2), total_price DECIMAL(12,2), notes TEXT, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX order_items_order_id_idx ON order_items(order_id);
CREATE INDEX order_items_product_id_idx ON order_items(product_id);
CREATE INDEX order_items_variant_id_idx ON order_items(variant_id);
CREATE TABLE production_orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES orders(id), order_item_id UUID REFERENCES order_items(id), product_id UUID REFERENCES products(id), variant_id UUID REFERENCES product_variants(id), status "ProductionStatus" NOT NULL DEFAULT 'PENDING', scheduled_start_date TIMESTAMP(3), started_at TIMESTAMP(3), estimated_completion TIMESTAMP(3), completed_at TIMESTAMP(3), observations TEXT, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX production_orders_order_id_idx ON production_orders(order_id);
CREATE INDEX production_orders_order_item_id_idx ON production_orders(order_item_id);
CREATE INDEX production_orders_status_idx ON production_orders(status);
CREATE TABLE deliveries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES orders(id), production_order_id UUID REFERENCES production_orders(id), status "DeliveryStatus" NOT NULL DEFAULT 'PENDING', scheduled_at TIMESTAMP(3), delivered_at TIMESTAMP(3), recipient_name TEXT, recipient_phone TEXT, address TEXT, evidence_url TEXT, incident_description TEXT, observations TEXT, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX deliveries_order_id_idx ON deliveries(order_id);
CREATE INDEX deliveries_production_order_id_idx ON deliveries(production_order_id);
CREATE INDEX deliveries_status_idx ON deliveries(status);

CREATE TABLE crm_pipeline (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE, stage "LeadStatus" NOT NULL, entered_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, exited_at TIMESTAMP(3), notes TEXT, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX crm_pipeline_lead_id_idx ON crm_pipeline(lead_id);
CREATE INDEX crm_pipeline_stage_idx ON crm_pipeline(stage);
CREATE TABLE crm_notes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), author_id UUID REFERENCES users(id), lead_id UUID REFERENCES leads(id), client_id UUID REFERENCES clients(id), order_id UUID REFERENCES orders(id), content TEXT NOT NULL, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX crm_notes_author_id_idx ON crm_notes(author_id);
CREATE INDEX crm_notes_lead_id_idx ON crm_notes(lead_id);
CREATE INDEX crm_notes_client_id_idx ON crm_notes(client_id);
CREATE INDEX crm_notes_order_id_idx ON crm_notes(order_id);
CREATE TABLE tasks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), assigned_user_id UUID REFERENCES users(id), lead_id UUID REFERENCES leads(id), client_id UUID REFERENCES clients(id), order_id UUID REFERENCES orders(id), title TEXT NOT NULL, description TEXT, status "TaskStatus" NOT NULL DEFAULT 'PENDING', priority "TaskPriority" NOT NULL DEFAULT 'MEDIUM', due_at TIMESTAMP(3), completed_at TIMESTAMP(3), created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX tasks_assigned_user_id_idx ON tasks(assigned_user_id);
CREATE INDEX tasks_lead_id_idx ON tasks(lead_id);
CREATE INDEX tasks_client_id_idx ON tasks(client_id);
CREATE INDEX tasks_order_id_idx ON tasks(order_id);
CREATE INDEX tasks_status_idx ON tasks(status);

CREATE TABLE hero_slides (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), title TEXT NOT NULL, subtitle TEXT, description TEXT, desktop_image_url TEXT, tablet_image_url TEXT, mobile_image_url TEXT, alt_text TEXT, primary_button_label TEXT, primary_button_url TEXT, secondary_button_label TEXT, secondary_button_url TEXT, display_order INTEGER NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT false, starts_at TIMESTAMP(3), ends_at TIMESTAMP(3), created_by UUID REFERENCES users(id), updated_by UUID REFERENCES users(id), created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX hero_slides_is_active_idx ON hero_slides(is_active);
CREATE TABLE faq (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), question TEXT NOT NULL, answer TEXT NOT NULL, category TEXT, display_order INTEGER NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT true, created_by UUID REFERENCES users(id), updated_by UUID REFERENCES users(id), created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE INDEX faq_is_active_idx ON faq(is_active);
CREATE TABLE settings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), key TEXT NOT NULL UNIQUE, value JSONB NOT NULL, description TEXT, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP(3));
CREATE TABLE activity_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id), entity_type TEXT NOT NULL, entity_id UUID, action TEXT NOT NULL, metadata JSONB, result TEXT, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX activity_logs_user_id_idx ON activity_logs(user_id);
CREATE INDEX activity_logs_entity_type_entity_id_idx ON activity_logs(entity_type, entity_id);
