import { CrmLeadStatus, type Prisma, type PrismaClient } from '@prisma/client';
export class CrmRepository {
  constructor(private readonly prisma: PrismaClient) {}
  companies(search: string, skip: number, take: number) { const where: Prisma.CompanyWhereInput = search ? { OR: [{ businessName: { contains: search, mode: 'insensitive' } }, { commercialName: { contains: search, mode: 'insensitive' } }] } : {}; return Promise.all([this.prisma.company.findMany({ where, skip, take, orderBy: { createdAt: 'desc' } }), this.prisma.company.count({ where })]); }
  contacts(search: string, skip: number, take: number) { const where: Prisma.ContactWhereInput = search ? { OR: [{ firstName: { contains: search, mode: 'insensitive' } }, { lastName: { contains: search, mode: 'insensitive' } }] } : {}; return Promise.all([this.prisma.contact.findMany({ where, skip, take, include: { company: true }, orderBy: { createdAt: 'desc' } }), this.prisma.contact.count({ where })]); }
  leads(search: string, skip: number, take: number) { const where: Prisma.LeadWhereInput = search ? { OR: [{ source: { contains: search, mode: 'insensitive' } }, { company: { businessName: { contains: search, mode: 'insensitive' } } }] } : {}; return Promise.all([this.prisma.lead.findMany({ where, skip, take, include: { company: true, contact: true }, orderBy: { createdAt: 'desc' } }), this.prisma.lead.count({ where })]); }
  create(kind: 'companies'|'contacts'|'leads', data: object) { if (kind === 'companies') return this.prisma.company.create({ data: data as Prisma.CompanyCreateInput }); if (kind === 'contacts') return this.prisma.contact.create({ data: data as Prisma.ContactUncheckedCreateInput }); return this.prisma.lead.create({ data: data as Prisma.LeadUncheckedCreateInput }); }
  update(kind: 'companies'|'contacts'|'leads', id: string, data: object) { if (kind === 'companies') return this.prisma.company.update({ where: { id }, data }); if (kind === 'contacts') return this.prisma.contact.update({ where: { id }, data }); return this.prisma.lead.update({ where: { id }, data }); }
  remove(kind: 'companies'|'contacts'|'leads', id: string) { if (kind === 'companies') return this.prisma.company.delete({ where: { id } }); if (kind === 'contacts') return this.prisma.contact.delete({ where: { id } }); return this.prisma.lead.delete({ where: { id } }); }
  dashboard() { return Promise.all([CrmLeadStatus.NEW, CrmLeadStatus.WON, CrmLeadStatus.LOST].map((crmStatus) => this.prisma.lead.count({ where: { crmStatus } }))); }
}
